# Generated by Django 6.0.1 on 2026-04-14 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_is_active_resume_one_active_resume_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(blank=True, max_length=255, null=True)),
                ('target_role', models.CharField(blank=True, max_length=255, null=True)),
                ('timeline_total', models.CharField(blank=True, max_length=50, null=True)),
                ('target_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_path', to='resumes.resume')),
            ],
            options={
                'db_table': 'career_pathways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('current', 'Current'), ('upcoming', 'Upcoming'), ('future', 'Future')], default='upcoming', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='resumes.careerpathway')),
            ],
            options={
                'db_table': 'career_stages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextBestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_type', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_skills', models.JSONField(blank=True, default=list)),
                ('target_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_step', to='resumes.resume')),
            ],
            options={
                'db_table': 'next_best_steps',
                'ordering': ['-created_at'],
            },
        ),
    ]
