# Generated by Django 6.0.4 on 2026-06-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_careerpathway_careerstage_nextbeststep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('courses', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendation', to='resumes.nextbeststep')),
            ],
            options={
                'db_table': 'skill_course_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
